version: '3'

services:
  leaguesync:
    build: .
    container_name: leaguesync-sync

    volumes:
      - leaguesync-data:/opt/leaguesync-data

    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: leaguesync-nginx
    volumes:
      - leaguesync-data:/usr/share/nginx/html:ro

    labels:
      caddy: p13sync.do.jointheleague.org
      caddy.reverse_proxy: "{{upstreams 80}}"
      
      caddy.basicauth: "*"
      caddy.basicauth.code: ${PASSWORD}

    restart: unless-stopped

    networks:
      - caddy



volumes:
  leaguesync-data:

networks:
  caddy:
    external: true


